#include <iostream>

#include "core.h"
#include "engine.h"

int main() {
  Board* board = new Board(
      {
          Piece(Color::black, PieceType::rook),
          Piece(Color::black, PieceType::knight),
          Piece(Color::black, PieceType::bishop),
          Piece(Color::black, PieceType::queen),
          Piece(Color::black, PieceType::king),
          Piece(Color::black, PieceType::bishop),
          Piece(Color::black, PieceType::knight),
          Piece(Color::black, PieceType::rook),
          Piece(Color::black, PieceType::pawn),
          Piece(Color::black, PieceType::pawn),
          Piece(Color::black, PieceType::pawn),
          Piece(Color::black, PieceType::pawn),
          Piece(Color::black, PieceType::pawn),
          Piece(Color::black, PieceType::pawn),
          Piece(Color::black, PieceType::pawn),
          Piece(Color::black, PieceType::pawn),
          Piece(Color::none, PieceType::empty),
          Piece(Color::none, PieceType::empty),
          Piece(Color::none, PieceType::empty),
          Piece(Color::none, PieceType::empty),
          Piece(Color::none, PieceType::empty),
          Piece(Color::none, PieceType::empty),
          Piece(Color::none, PieceType::empty),
          Piece(Color::none, PieceType::empty),
          Piece(Color::none, PieceType::empty),
          Piece(Color::none, PieceType::empty),
          Piece(Color::none, PieceType::empty),
          Piece(Color::none, PieceType::empty),
          Piece(Color::none, PieceType::empty),
          Piece(Color::none, PieceType::empty),
          Piece(Color::none, PieceType::empty),
          Piece(Color::none, PieceType::empty),
          Piece(Color::none, PieceType::empty),
          Piece(Color::none, PieceType::empty),
          Piece(Color::none, PieceType::empty),
          Piece(Color::none, PieceType::empty),
          Piece(Color::none, PieceType::empty),
          Piece(Color::none, PieceType::empty),
          Piece(Color::none, PieceType::empty),
          Piece(Color::none, PieceType::empty),
          Piece(Color::none, PieceType::empty),
          Piece(Color::none, PieceType::empty),
          Piece(Color::none, PieceType::empty),
          Piece(Color::none, PieceType::empty),
          Piece(Color::none, PieceType::empty),
          Piece(Color::none, PieceType::empty),
          Piece(Color::none, PieceType::empty),
          Piece(Color::none, PieceType::empty),
          Piece(Color::white, PieceType::pawn),
          Piece(Color::white, PieceType::pawn),
          Piece(Color::white, PieceType::pawn),
          Piece(Color::white, PieceType::pawn),
          Piece(Color::white, PieceType::pawn),
          Piece(Color::white, PieceType::pawn),
          Piece(Color::white, PieceType::pawn),
          Piece(Color::white, PieceType::pawn),
          Piece(Color::white, PieceType::rook),
          Piece(Color::white, PieceType::knight),
          Piece(Color::white, PieceType::bishop),
          Piece(Color::white, PieceType::queen),
          Piece(Color::white, PieceType::king),
          Piece(Color::white, PieceType::bishop),
          Piece(Color::white, PieceType::knight),
          Piece(Color::white, PieceType::rook),
      },
      Color::white);

  std::cout << "Paarthfish" << std::endl;
  std::cout << NegaMax(-1000, 1000, 10, board);
  return 0;
}